version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: lappis
            MONGO_INITDB_ROOT_PASSWORD: lappis
            MONGO_INITDB_DATABASE: mongo_database 
        ports:
            - 27017:27017

            