FROM python:3.9

#RUN mkdir -p app
WORKDIR /src
 
COPY requirements.txt .
#WORKDIR /src
RUN pip install -r requirements.txt

COPY . .
 
EXPOSE 8000  

#CMD python main.py
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
